### ISSUE TITLE
Certificate Error when trying to fetch password

### ISSUE THREAD

**Issue by mrmusixx** [Morluktom/LG_ESS#1]
Hello Morluktom,

I keep getting errors when trying to get the password out of my LG ESS.

In FHEM interface, using ...

define myEss LG_ESS GettingPassword

... I keep getting:

LG ESS: could not fetch password. 
Errorcode: 
https://192.168.23.1/v1/user/setting/read/password: Can't connect(2) to https://192.168.23.1:443: SSL connect attempt failed error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed SSL connect attempt failed error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

LG ESS firmware is most current as of today.
Trying to access the same thing with "wget" reveals some more details:

wget https://localhost/v1/user/setting/read/password --no-check-certificate
--2021-01-07 20:12:00--  https://localhost/v1/user/setting/read/password
Auflösen des Hostnamens localhost (localhost) … 192.168.23.1
Verbindungsaufbau zu localhost (localhost)|192.168.23.1|:443 … verbunden.
WARNUNG: Das Zertifikat von localhost kann nicht geprüft werden, ausgestellt von »emailAddress=enervu.ess@lge.com,CN=localhost,OU=ESS,O=LGE,L=Incheon,ST=Incheon,C=KR«:.
  Ein selbst-signiertes Zertifikat wurde gefunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2021-01-07 20:12:01 FEHLER 404: Not Found.

(Note: I temporarily modified "localhost" to point to 192.168.23.1, just for the record.)

What's going wrong? Why is it "404 - Not found"??

Kind regards

Ansgar

**Comment by Morluktom** [comment]
Hi, 
please try the following Programm.
[LG_Ess_Password.zip](https://github.com/Morluktom/LG_ESS/files/5784224/LG_Ess_Password.zip)
Connect your Laptop direct to the WLAN of the LG-ESS.
Start the LG_ESS_Password.exe.
Regards
Tom

**Comment by mrmusixx** [comment]
Hello,

I found the problem, and a fix that works - at least for me, don't know if it is the best, or working for everyone. More, I'm unfamiliar with Pull requests and don't have Git installed here on the respective machine, so I'll drop my description just here.
Problem seems to be a wrong passing of parameters to HttpUtils, when it comes to "sslargs".
Original code snippet of the 1st occurrence:

`sub LG_ESS_GettingPassword($)
{
	my ($hash, $def)				= @_;
	my $name						= $hash->{NAME};
	my $PollingTimeout				= 10;
	
	# Stop the current timer
	RemoveInternalTimer($hash);

	# Set status of fhem module
	$hash->{STATE} = "Getting Password";

	my $url = "https://192.168.23.1/v1/user/setting/read/password";
	my $content = '{"key": "lgepmsuser!@#"}';

	my $sslPara->{sslargs} = { verify_hostname => 0};
	my $param = {
					url			=> $url,
					timeout		=> $PollingTimeout,
					data		=> $content,
					method		=> "POST",
					sslargs		=> $sslPara,
					header		=> "Content-Type: application/json",
				};

	#Function call
	my($err, $data) = HttpUtils_BlockingGet($param);
`

Problem is the 
`					sslargs		=> $sslPara,
`
line, as a few lines earlier, you set
`	my $sslPara->{sslargs} = { verify_hostname => 0};
`

So when setting "sslargs", it should likely read:
`					sslargs		=> $sslPara->{sslargs},
`
instead.
And there are 3 more occurrences of the same throughout the file.
With these 4 places modified, it works like a charm here.
I found it out by making changes to the contents of 
`my $sslPara->{sslargs} = { verify_hostname => 0}`
which had no influence on the behaviour, obviously. Using Wireshark, I could see that the failure was always the same no matter what I entered there. I then stepped into the HttpUtils, located the place where the SSL communication is actually started, and replaced the call temporarily with some fixed parameters. This worked, so ith had to be some problem in passing parameters. Need to add I'm not really into Perl yet...

Actually, I chose to finally set 
`my $sslPara->{sslargs} = { verify_hostname => 0, SSL_verify_mode => 0 };`
i.e. bypassing all SSL checking for my use case, as for in-house use, MITM attacks tend to be rare. :)
Hope this is of help for anyone.

mistermusixx

**Comment by Morluktom** [comment]
Thanks for your work, is fixed
